[package]
name = "blog"
version = "0.0.0"
authors = ["konojunya <junya.developer@gmail.com>"]
description = "blog system"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
